version: '4.1.{build}'

environment:
  CMAKE_PATH: c:\projects\TapTools\cmake-3.4.1-win32-x86
#  encrypted_key:
#    secure: wMFDidPMGaYZm9nzEn9OSoPa2BIRrLw5bpKkvcGJCY8=
#  encrypted_iv:
#    secure: iXPMeWgtvO5yvxY5yQodIH7+AAZhMjjLIAgUw429d7A=

configuration: Release

#shallow_clone: true # clone repository as zip archive

install:
  - curl --retry 10 -sO https://cmake.org/files/v3.4/cmake-3.4.1-win32-x86.zip
  - 7z x cmake-3.4.1-win32-x86.zip -y > nul
#  - curl --retry 10 -sO http://freefr.dl.sourceforge.net/project/winscp/WinSCP/5.7.5/winscp575automation.zip
#  - 7z x winscp575automation.zip -y > nul

platform:
  - Win32
  - x64

build_script:
  - ps: c:\projects\TapTools\source\build.ps1
#  - ps: c:\projects\JamomaMax\script\build-appveyor.ps1



# deploy_script:
#  - ps: c:\projects\JamomaMax\script\deploy-appveyor.ps1

# artifacts:
#   - name: Jamoma for Max - Windows $(platform)
#     path: JamomaMax-*.zip
#   - name: Log files
#     path: '*.log'

